module.exports = {
  plugins: {
    'postcss-sorting': {
      'properties-order': [
        // Positioning
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'z-index',
        
        // Display & Box Model
        'display',
        'float',
        'clear',
        'overflow',
        'overflow-x',
        'overflow-y',
        'clip',
        'zoom',
        
        // Box Model
        'box-sizing',
        'width',
        'height',
        'min-width',
        'min-height',
        'max-width',
        'max-height',
        
        // Margin & Padding
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        
        // Border
        'border',
        'border-width',
        'border-style',
        'border-color',
        'border-top',
        'border-top-width',
        'border-top-style',
        'border-top-color',
        'border-right',
        'border-right-width',
        'border-right-style',
        'border-right-color',
        'border-bottom',
        'border-bottom-width',
        'border-bottom-style',
        'border-bottom-color',
        'border-left',
        'border-left-width',
        'border-left-style',
        'border-left-color',
        'border-radius',
        'border-top-left-radius',
        'border-top-right-radius',
        'border-bottom-right-radius',
        'border-bottom-left-radius',
        'border-image',
        'border-image-source',
        'border-image-slice',
        'border-image-width',
        'border-image-outset',
        'border-image-repeat',
        
        // Background
        'background',
        'background-color',
        'background-image',
        'background-repeat',
        'background-attachment',
        'background-position',
        'background-position-x',
        'background-position-y',
        'background-clip',
        'background-origin',
        'background-size',
        
        // Font & Text
        'color',
        'font',
        'font-family',
        'font-size',
        'font-style',
        'font-variant',
        'font-weight',
        'font-stretch',
        'font-size-adjust',
        'line-height',
        'text-align',
        'text-align-last',
        'text-decoration',
        'text-indent',
        'text-justify',
        'text-outline',
        'text-transform',
        'text-wrap',
        'text-overflow',
        'text-shadow',
        'letter-spacing',
        'word-spacing',
        'white-space',
        'vertical-align',
        'word-wrap',
        'word-break',
        
        // Content
        'content',
        'quotes',
        'counter-reset',
        'counter-increment',
        'resize',
        'cursor',
        'user-select',
        'nav-index',
        'nav-up',
        'nav-right',
        'nav-down',
        'nav-left',
        
        // Table
        'table-layout',
        'empty-cells',
        'caption-side',
        'border-spacing',
        'border-collapse',
        
        // List
        'list-style',
        'list-style-position',
        'list-style-type',
        'list-style-image',
        
        // Animation & Transform
        'opacity',
        'transform',
        'transform-origin',
        'transition',
        'transition-property',
        'transition-duration',
        'transition-timing-function',
        'transition-delay',
        'animation',
        'animation-name',
        'animation-duration',
        'animation-timing-function',
        'animation-delay',
        'animation-iteration-count',
        'animation-direction',
        'animation-play-state',
        'animation-fill-mode',
        
        // Flexbox
        'flex',
        'flex-grow',
        'flex-shrink',
        'flex-basis',
        'flex-direction',
        'flex-wrap',
        'flex-flow',
        'justify-content',
        'align-items',
        'align-self',
        'align-content',
        
        // Grid
        'grid',
        'grid-template',
        'grid-template-columns',
        'grid-template-rows',
        'grid-template-areas',
        'grid-area',
        'grid-column',
        'grid-column-start',
        'grid-column-end',
        'grid-row',
        'grid-row-start',
        'grid-row-end',
        'grid-gap',
        'grid-column-gap',
        'grid-row-gap',
        'justify-items',
        'justify-self',
        'align-items',
        'align-self',
        'align-content',
        
        // Other
        'visibility',
        'clip',
        'filter',
        'backface-visibility',
        'perspective',
        'perspective-origin',
        'transform-style',
        'backface-visibility'
      ]
    }
  },
  parser: 'postcss-scss'
} 